on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:


jobs:
  generate-html-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set the destination directory for push event
        if: ${{ github.event_name == 'push' }}
        run: echo "destination_dir=doc/branch/${{ github.ref_name }}" >> $GITHUB_ENV

      - name: set the destination directory for PR event
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "destination_dir=doc/pr/${{ github.event.pull_request.number }}-${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Coq
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: 8.19
          ocaml_version: 4.14-flambda
          before_install: |
            opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
            opam update
            opam install -y coq-rocqnavi
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "Build project"
              make -j2
            endGroup
          after_script: |
            mkdir -p html
            coq2html -d html -title "TITLE" -coqlib https://coq.inria.fr/doc/V8.18.0/stdlib/ \
              -Q theories Sample theories/*.v theories/*.glob

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
          destination_dir: ${{ env.destination_dir }}
          keep_files: true
          user_name: github-actions
          user_email: github-actions@github.com