on:
  pull_request:


jobs:
  generate-html-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set the variables for push event
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "branch_name="${{ github.ref_name }} >> $GITHUB_ENV
          branch_name=${{ github.ref_name }}
          echo $branch_name
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$short_sha" >> $GITHUB_ENV
          echo $short_sha
          echo "destination_dir=sample_"$branch_name_$short_sha >> $GITHUB_ENV

      - name: set the variables for PR event
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "branch_name="${{ github.head_ref }} >> $GITHUB_ENV
          branch_name=${{ github.head_ref }}
          echo $branch_name
          echo "destination_dir=sample_$branch_name" >> $GITHUB_ENV

      - name: Setup Coq
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: 8.19
          ocaml_version: 4.14-flambda
          before_install: |
            opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
            opam update
            opam install -y coq-rocqnavi
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "Build project"
              make -j2
            endGroup
          after_script: |
            mkdir -p artifact/${{ env.destination_dir }}
            coq2html -d artifact/${{ env.destination_dir }} -title "TITLE" -coqlib https://coq.inria.fr/doc/V8.18.0/stdlib/ \
              -Q theories Sample theories/*.v theories/*.glob

      - name: Upload htmldoc as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.destination_dir }}
          path: |
            artifact
